[package]
name = "iron-canvas-export"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[features]
default = ["svg", "pdf"]
svg = []
pdf = []

[dependencies]
iron-canvas-core = { path = "../iron-canvas-core" }
ttf-parser = { workspace = true }

[dev-dependencies]
iron-canvas-datagrid = { path = "../iron-canvas-datagrid" }
