[package]
name = "iron-canvas-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
licence.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
ironcalc_base = { workspace = true }
serde = { workspace = true, features = ["derive"] }
bitflags = {workspace = true}

[dev-dependencies]
iron-canvas-recorder = { path = "../iron-canvas-recorder" }
iron-canvas-svg = { path = "../iron-canvas-svg" }
