[package]
name = "iron-canvas-recorder"
version.workspace = true
authors.workspace = true
edition.workspace = true
licence.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
iron-canvas-core = { path = "../iron-canvas-core" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
