//! Golden `.icr` fixture — regression sentinel for the on-disk format.
//!
//! The fixture is a hand-built `Recording` (no orchestrator) covering
//! one frame with a small, deterministic mix of `DrawOp`s. Its purpose:
//!
//! 1. Catch unintended changes to the serde representation — a serde-rename,
//!    a field reorder, or a variant addition shifts the bytes and the
//!    test fails with a one-line "regenerate" instruction.
//! 2. Give the standalone viewer (`web-test/recording-viewer.html`) a
//!    fixed file to drag-drop during manual smoke tests.
//!
//! # Regenerating
//!
//! Run `ICR_REGEN=1 cargo test -p iron-canvas-recorder --test golden_fixture`
//! to write the freshly-generated bytes back to disk. Inspect the diff
//! (`git diff tests/fixtures/fresh_paint.icr`) before committing — if
//! anything other than `iron_canvas_version` moved, the format changed
//! and `ICR_SCHEMA_VERSION` may need a bump.

#![allow(clippy::unwrap_used)]
#![allow(clippy::expect_used)]

use std::path::Path;

use iron_canvas_core::geometry::pixel_rect::PixelRect;
use iron_canvas_core::geometry::prim::{Line, Point, Span};
use iron_canvas_core::painter::{GroupClass, TextAlign, TextBaseline};
use iron_canvas_core::theme::CanvasTheme;
use iron_canvas_core::PaintRegimeTag;

use iron_canvas_recorder::recording::{Frame, IcrHeader, Recording, ThemeSnapshot};
use iron_canvas_recorder::DrawOp;

const FIXTURE_PATH: &str = "tests/fixtures/fresh_paint.icr";
const OVERLAY_FIXTURE_PATH: &str = "tests/fixtures/overlay_paint.icr";

/// Builds a deterministic Recording covering one Fresh frame. The shape
/// is hand-picked to exercise every `DrawOp` variant the viewer needs to
/// dispatch on — RectFill / Stroke / Dashed, line variants, clip
/// bracket, FillText, Blit, BeginGroup/EndGroup, and the unit variants
/// (InvalidateCache / ResetTextDefaults). The grid ops mirror the
/// `render_grid` section order — setup, then nested `Cells` / `FrozenSep`
/// / `Headers` / `Corner` brackets — so the fixture stands in for a
/// real renderer output as well as the wire-format regression sentinel.
/// Coordinates fit inside the header's declared 200×100 canvas so the
/// viewer renders the full scene without overflow.
fn build_fixture() -> Recording {
    let r = |x: i32, y: i32, w: i32, h: i32| PixelRect {
        top_left: Point { x, y },
        width: w,
        height: h,
    };

    let grid_ops = vec![
        DrawOp::BeginGroup {
            class: GroupClass::Grid,
        },
        DrawOp::ApplyDprTransform { dpr: 1 },
        DrawOp::InvalidateCache,
        DrawOp::ResetTextDefaults,
        DrawOp::BeginGroup {
            class: GroupClass::Cells,
        },
        DrawOp::RectFill {
            rect: r(0, 0, 200, 100),
            color: "#FFFFFF".to_string(),
        },
        DrawOp::StrokeHLine {
            span: Span { from: 0, to: 200 },
            y: 20.0,
            color: "#CCCCCC".to_string(),
            width: 1.0,
        },
        DrawOp::StrokeVLine {
            x: 80.0,
            span: Span { from: 0, to: 100 },
            color: "#CCCCCC".to_string(),
            width: 1.0,
        },
        DrawOp::EndGroup,
        DrawOp::BeginGroup {
            class: GroupClass::FrozenSep,
        },
        DrawOp::StrokeLine {
            line: Line::H {
                span: Span { from: 0, to: 200 },
                y: 0,
            },
            color: "#333333".to_string(),
            width: 1.0,
        },
        DrawOp::EndGroup,
        DrawOp::BeginGroup {
            class: GroupClass::Headers,
        },
        DrawOp::PushClip {
            rect: r(0, 0, 80, 20),
        },
        DrawOp::FillText {
            text: "A1".to_string(),
            x: 4.0,
            y: 4.0,
            font_css: "12px sans-serif".to_string(),
            color: "#222222".to_string(),
            align: TextAlign::Start,
            baseline: TextBaseline::Top,
        },
        DrawOp::PopClip,
        DrawOp::StrokeTextHLine {
            x1: 0.0,
            x2: 80.0,
            y: 19.0,
            color: "#888888".to_string(),
            width: 0.5,
        },
        DrawOp::RectStroke {
            rect: r(0, 0, 80, 20),
            color: "#000000".to_string(),
            width: 1.0,
        },
        DrawOp::EndGroup,
        DrawOp::BeginGroup {
            class: GroupClass::Corner,
        },
        DrawOp::Blit {
            src: r(0, 20, 200, 80),
            dst: r(0, 0, 200, 80),
        },
        DrawOp::EndGroup,
        DrawOp::EndGroup,
    ];

    let overlay_ops = vec![
        DrawOp::ClearRect {
            rect: r(0, 0, 200, 100),
        },
        DrawOp::RectDashed {
            rect: r(0, 0, 80, 20),
            color: "#1E6FD9".to_string(),
            width: 1.5,
        },
    ];

    let header = IcrHeader::new(
        200.0,
        100.0,
        1,
        ThemeSnapshot::from(&CanvasTheme::light()),
        0, // deterministic — never reads wall clock
    );

    let mut rec = Recording::new(header);
    rec.push_frame(Frame {
        frame_idx: 0,
        t_ms: 0,
        regime: PaintRegimeTag::Fresh,
        // STRUCTURAL bit set — matches what a first-paint frame would
        // record after a model push.
        signals: 0b0100,
        grid_ops,
        overlay_ops,
    });
    rec
}

#[test]
fn golden_fixture_round_trip_matches_disk() {
    let rec = build_fixture();
    let bytes = rec.serialize().expect("serialize");
    let fixture_path = Path::new(env!("CARGO_MANIFEST_DIR")).join(FIXTURE_PATH);

    if std::env::var("ICR_REGEN").is_ok() {
        std::fs::create_dir_all(fixture_path.parent().unwrap()).unwrap();
        std::fs::write(&fixture_path, &bytes)
            .unwrap_or_else(|e| panic!("write fixture {}: {}", fixture_path.display(), e));
        println!("wrote {} ({} bytes)", fixture_path.display(), bytes.len());
        return;
    }

    let on_disk = std::fs::read(&fixture_path).unwrap_or_else(|e| {
        panic!(
            "read fixture {}: {} \
             (first run? regenerate with ICR_REGEN=1 cargo test ...)",
            fixture_path.display(),
            e
        )
    });
    assert_eq!(
        on_disk, bytes,
        "fixture drift detected at {}; if the format change is intentional, \
         regenerate with `ICR_REGEN=1 cargo test -p iron-canvas-recorder \
         --test golden_fixture` and commit the new file.",
        fixture_path.display()
    );

    // Sanity: the disk bytes also round-trip through deserialize.
    let restored = Recording::deserialize(&on_disk).expect("deserialize disk fixture");
    assert_eq!(restored, rec);
}

/// Builds a deterministic Recording focused on the overlay layer's
/// decoration brackets. One frame whose `overlay_ops` walks all 8
/// `GroupClass` variants the overlay layer emits, each with a single
/// cheap op inside so the brackets aren't empty. The grid layer stays
/// empty — this fixture stands in for an `OverlayOnly` recording.
fn build_overlay_fixture() -> Recording {
    let r = |x: i32, y: i32, w: i32, h: i32| PixelRect {
        top_left: Point { x, y },
        width: w,
        height: h,
    };

    let overlay_ops = vec![
        DrawOp::BeginGroup {
            class: GroupClass::Overlay,
        },
        DrawOp::BeginGroup {
            class: GroupClass::SelectionFill,
        },
        DrawOp::RectFill {
            rect: r(0, 0, 80, 20),
            color: "#1E6FD933".to_string(),
        },
        DrawOp::EndGroup,
        DrawOp::BeginGroup {
            class: GroupClass::ActiveCellRepaint,
        },
        DrawOp::ClearRect {
            rect: r(0, 0, 80, 20),
        },
        DrawOp::EndGroup,
        DrawOp::BeginGroup {
            class: GroupClass::SelectionStroke,
        },
        DrawOp::RectStroke {
            rect: r(0, 0, 80, 20),
            color: "#1E6FD9".to_string(),
            width: 2.0,
        },
        DrawOp::EndGroup,
        DrawOp::BeginGroup {
            class: GroupClass::HeaderHighlights,
        },
        DrawOp::RectFill {
            rect: r(0, 0, 80, 4),
            color: "#1E6FD955".to_string(),
        },
        DrawOp::EndGroup,
        DrawOp::BeginGroup {
            class: GroupClass::Autofill,
        },
        DrawOp::RectFill {
            rect: r(76, 16, 4, 4),
            color: "#1E6FD9".to_string(),
        },
        DrawOp::EndGroup,
        DrawOp::BeginGroup {
            class: GroupClass::Clipboard,
        },
        DrawOp::RectDashed {
            rect: r(0, 20, 80, 20),
            color: "#000000".to_string(),
            width: 1.0,
        },
        DrawOp::EndGroup,
        DrawOp::BeginGroup {
            class: GroupClass::PointMode,
        },
        DrawOp::RectStroke {
            rect: r(80, 0, 80, 20),
            color: "#22BB22".to_string(),
            width: 1.5,
        },
        DrawOp::EndGroup,
        DrawOp::BeginGroup {
            class: GroupClass::FormulaRefs,
        },
        DrawOp::RectStroke {
            rect: r(80, 20, 80, 20),
            color: "#BB2222".to_string(),
            width: 1.5,
        },
        DrawOp::EndGroup,
        DrawOp::EndGroup,
    ];

    let header = IcrHeader::new(
        200.0,
        100.0,
        1,
        ThemeSnapshot::from(&CanvasTheme::light()),
        0,
    );

    let mut rec = Recording::new(header);
    rec.push_frame(Frame {
        frame_idx: 0,
        t_ms: 0,
        regime: PaintRegimeTag::Fresh,
        signals: 0b1000, // OVERLAY bit
        grid_ops: Vec::new(),
        overlay_ops,
    });
    rec
}

#[test]
fn overlay_paint_round_trip_matches_disk() {
    let rec = build_overlay_fixture();
    let bytes = rec.serialize().expect("serialize");
    let fixture_path = Path::new(env!("CARGO_MANIFEST_DIR")).join(OVERLAY_FIXTURE_PATH);

    if std::env::var("ICR_REGEN").is_ok() {
        std::fs::create_dir_all(fixture_path.parent().unwrap()).unwrap();
        std::fs::write(&fixture_path, &bytes)
            .unwrap_or_else(|e| panic!("write fixture {}: {}", fixture_path.display(), e));
        println!("wrote {} ({} bytes)", fixture_path.display(), bytes.len());
        return;
    }

    let on_disk = std::fs::read(&fixture_path).unwrap_or_else(|e| {
        panic!(
            "read fixture {}: {} \
             (first run? regenerate with ICR_REGEN=1 cargo test ...)",
            fixture_path.display(),
            e
        )
    });
    assert_eq!(
        on_disk, bytes,
        "overlay fixture drift at {}; regenerate with `ICR_REGEN=1 cargo test \
         -p iron-canvas-recorder --test golden_fixture` if intentional.",
        fixture_path.display()
    );
    let restored = Recording::deserialize(&on_disk).expect("deserialize disk fixture");
    assert_eq!(restored, rec);
}

#[test]
fn overlay_frame_has_decoration_subgroups() {
    // All 8 overlay decoration variants must appear inside the Overlay
    // group of a frame that exercises every decoration layer. Catches
    // accidental drops of a `begin_group` call when overlay decorations
    // are added or shuffled in `LayerBase::paint_overlay_layer`.
    let rec = build_overlay_fixture();
    let frame = rec.frames.first().expect("fixture has one frame");
    let variants: std::collections::HashSet<&str> = frame
        .overlay_ops
        .iter()
        .filter_map(|op| match op {
            DrawOp::BeginGroup { class } => Some(class.as_str()),
            _ => None,
        })
        .collect();
    for required in [
        "overlay",
        "selection-fill",
        "selection-stroke",
        "autofill",
        "clipboard",
        "point-mode",
        "formula-refs",
        "active-cell-repaint",
        "header-highlights",
    ] {
        assert!(
            variants.contains(required),
            "overlay_ops missing BeginGroup({required:?}); present: {variants:?}",
        );
    }
}

#[test]
fn fresh_frame_has_grid_sections() {
    // The fixture stands in for a real `render_grid` output; every
    // section bracket the renderer opens must appear inside the Grid
    // group of frame 0. This catches accidental drops of a `begin_group`
    // call when sections are added or shuffled in the renderer.
    let rec = build_fixture();
    let frame = rec.frames.first().expect("fixture has one Fresh frame");
    let variants: std::collections::HashSet<&str> = frame
        .grid_ops
        .iter()
        .filter_map(|op| match op {
            DrawOp::BeginGroup { class } => Some(class.as_str()),
            _ => None,
        })
        .collect();
    for required in ["grid", "cells", "frozen-sep", "headers", "corner"] {
        assert!(
            variants.contains(required),
            "grid_ops missing BeginGroup({required:?}); present: {variants:?}",
        );
    }
}
