//! Golden `.icr` fixture — regression sentinel for the on-disk format.
//!
//! The fixture is a hand-built `Recording` (no orchestrator) covering
//! one frame with a small, deterministic mix of `DrawOp`s. Its purpose:
//!
//! 1. Catch unintended changes to the serde representation — a serde-rename,
//!    a field reorder, or a variant addition shifts the bytes and the
//!    test fails with a one-line "regenerate" instruction.
//! 2. Give the standalone viewer (`web-test/recording-viewer.html`) a
//!    fixed file to drag-drop during manual smoke tests.
//!
//! # Regenerating
//!
//! Run `ICR_REGEN=1 cargo test -p iron-canvas-recorder --test golden_fixture`
//! to write the freshly-generated bytes back to disk. Inspect the diff
//! (`git diff tests/fixtures/fresh_paint.icr`) before committing — if
//! anything other than `iron_canvas_version` moved, the format changed
//! and `ICR_SCHEMA_VERSION` may need a bump.

#![allow(clippy::unwrap_used)]
#![allow(clippy::expect_used)]

use std::path::Path;

use iron_canvas_core::geometry::pixel_rect::PixelRect;
use iron_canvas_core::geometry::prim::{Line, Point, Span};
use iron_canvas_core::painter::{GroupClass, TextAlign, TextBaseline};
use iron_canvas_core::theme::CanvasTheme;
use iron_canvas_core::PaintRegimeTag;

use iron_canvas_recorder::recording::{Frame, IcrHeader, Recording, ThemeSnapshot};
use iron_canvas_recorder::DrawOp;

const FIXTURE_PATH: &str = "tests/fixtures/fresh_paint.icr";

/// Builds a deterministic Recording covering one Fresh frame. The shape
/// is hand-picked to exercise every `DrawOp` variant the viewer needs to
/// dispatch on — RectFill / Stroke / Dashed, line variants, clip
/// bracket, FillText, Blit, BeginGroup/EndGroup, and the unit variants
/// (InvalidateCache / ResetTextDefaults). Coordinates fit inside the
/// header's declared 200×100 canvas so the viewer renders the full
/// scene without overflow.
fn build_fixture() -> Recording {
    let r = |x: i32, y: i32, w: i32, h: i32| PixelRect {
        top_left: Point { x, y },
        width: w,
        height: h,
    };

    let grid_ops = vec![
        DrawOp::BeginGroup {
            class: GroupClass::Grid,
        },
        DrawOp::ApplyDprTransform { dpr: 1 },
        DrawOp::InvalidateCache,
        DrawOp::ResetTextDefaults,
        DrawOp::RectFill {
            rect: r(0, 0, 200, 100),
            color: "#FFFFFF".to_string(),
        },
        DrawOp::StrokeHLine {
            span: Span { from: 0, to: 200 },
            y: 20.0,
            color: "#CCCCCC".to_string(),
            width: 1.0,
        },
        DrawOp::StrokeVLine {
            x: 80.0,
            span: Span { from: 0, to: 100 },
            color: "#CCCCCC".to_string(),
            width: 1.0,
        },
        DrawOp::StrokeLine {
            line: Line::H {
                span: Span { from: 0, to: 200 },
                y: 0,
            },
            color: "#333333".to_string(),
            width: 1.0,
        },
        DrawOp::PushClip {
            rect: r(0, 0, 80, 20),
        },
        DrawOp::FillText {
            text: "A1".to_string(),
            x: 4.0,
            y: 4.0,
            font_css: "12px sans-serif".to_string(),
            color: "#222222".to_string(),
            align: TextAlign::Start,
            baseline: TextBaseline::Top,
        },
        DrawOp::PopClip,
        DrawOp::StrokeTextHLine {
            x1: 0.0,
            x2: 80.0,
            y: 19.0,
            color: "#888888".to_string(),
            width: 0.5,
        },
        DrawOp::RectStroke {
            rect: r(0, 0, 80, 20),
            color: "#000000".to_string(),
            width: 1.0,
        },
        DrawOp::Blit {
            src: r(0, 20, 200, 80),
            dst: r(0, 0, 200, 80),
        },
        DrawOp::EndGroup,
    ];

    let overlay_ops = vec![
        DrawOp::ClearRect {
            rect: r(0, 0, 200, 100),
        },
        DrawOp::RectDashed {
            rect: r(0, 0, 80, 20),
            color: "#1E6FD9".to_string(),
            width: 1.5,
        },
    ];

    let header = IcrHeader::new(
        200.0,
        100.0,
        ThemeSnapshot::from(&CanvasTheme::light()),
        0, // deterministic — never reads wall clock
    );

    let mut rec = Recording::new(header);
    rec.push_frame(Frame {
        frame_idx: 0,
        t_ms: 0,
        regime: PaintRegimeTag::Fresh,
        // STRUCTURAL bit set — matches what a first-paint frame would
        // record after a model push.
        signals: 0b0100,
        grid_ops,
        overlay_ops,
    });
    rec
}

#[test]
fn golden_fixture_round_trip_matches_disk() {
    let rec = build_fixture();
    let bytes = rec.serialize().expect("serialize");
    let fixture_path = Path::new(env!("CARGO_MANIFEST_DIR")).join(FIXTURE_PATH);

    if std::env::var("ICR_REGEN").is_ok() {
        std::fs::create_dir_all(fixture_path.parent().unwrap()).unwrap();
        std::fs::write(&fixture_path, &bytes)
            .unwrap_or_else(|e| panic!("write fixture {}: {}", fixture_path.display(), e));
        println!("wrote {} ({} bytes)", fixture_path.display(), bytes.len());
        return;
    }

    let on_disk = std::fs::read(&fixture_path).unwrap_or_else(|e| {
        panic!(
            "read fixture {}: {} \
             (first run? regenerate with ICR_REGEN=1 cargo test ...)",
            fixture_path.display(),
            e
        )
    });
    assert_eq!(
        on_disk, bytes,
        "fixture drift detected at {}; if the format change is intentional, \
         regenerate with `ICR_REGEN=1 cargo test -p iron-canvas-recorder \
         --test golden_fixture` and commit the new file.",
        fixture_path.display()
    );

    // Sanity: the disk bytes also round-trip through deserialize.
    let restored = Recording::deserialize(&on_disk).expect("deserialize disk fixture");
    assert_eq!(restored, rec);
}
